#!/bin/zsh

# ┌───────────────────────────────────────────────────────────────────────────┐
# │                                BINDINGS                                   │
# └───────────────────────────────────────────────────────────────────────────┘

bindkey   -e					# emacs mode

bindkey   '[3~'	delete-char		# Delete

bindkey   '[1;2D'	backward-word		# sft ←
bindkey   '[1;3D'	backward-word		# alt ←
bindkey   '[1;5D'	backward-word		# ctr ←

bindkey   '[1;2C'	forward-word		# sft →
bindkey   '[1;3C'	forward-word		# alt →
bindkey   '[1;5C'	forward-word		# ctr →

bindkey   '[1;2A'	up-line-or-history	# sft ↑
bindkey   '[1;3A'	up-line-or-history	# alt ↑
bindkey   '[1;5A'	up-line-or-history	# ctr ↑

bindkey   '[1;2B'	down-line-or-history	# sft ↓ 
bindkey	  '[1;3B'	down-line-or-history	# alt ↓
bindkey   '[1;5B'	down-line-or-history	# ctr ↓

bindkey	  '[A'	history-beginning-search-backward # ↑
bindkey	  'OA'	history-beginning-search-backward #

bindkey	  '[B'	history-beginning-search-forward  # ↓
bindkey	  'OB'	history-beginning-search-forward  #

bindkey   'OF'	end-of-line		# End 
bindkey   '[4~'	end-of-line		#
bindkey   '[8~'	end-of-line		# 
bindkey   '[F'	end-of-line		# 
bindkey   'OH'	beginning-of-line	# Home
bindkey   '[1~'	beginning-of-line	#
bindkey   '[1~'	beginning-of-line	#
bindkey   '[7~'	beginning-of-line	#
bindkey   '[H'	beginning-of-line	#